# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $workflow: '@state_machine.content_publishing'
            App\Contract\NotificationChannelPort: '@App\Contract\Notification\NullNotificationChannel'

    App\Service\Avatar\AvatarProviderInterface:
        alias: App\Service\Avatar\DefaultAvatarProvider

    App\Service\Media\MediaProviderInterface:
        alias: App\Service\Media\DefaultMediaProvider

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude: '../src/Entity/'

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    role_service:
        alias: App\Service\RoleService
        public: true

    content_service:
        alias: App\Service\ContentService
        public: true

    visuals_links:
        class: ArrayObject
        arguments:
            - [
                'https://i.ibb.co/mC7sv0W/01.png',
                'https://i.ibb.co/ygqgFMV/02.png',
                'https://i.ibb.co/1KysC55/03.png',
                'https://i.ibb.co/64vFVfS/04.png',
                'https://i.ibb.co/TLDzmVf/05.png',
                'https://i.ibb.co/85LB6PW/06.png',
                'https://i.ibb.co/fDbmdMM/07.png',
                'https://i.ibb.co/tqMNGtX/08.png',
                'https://i.ibb.co/xF1QQXk/09.png',
                'https://i.ibb.co/LPYBSBX/10.png',
                'https://i.ibb.co/Fn2HJJQ/11.png',
                'https://i.ibb.co/TYPWsLQ/12.png'
              ]
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
